name: Build and Test

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yaml
          up-flags: -d

      - name: Users API tests.
        run: |
          echo "Running Playwright to execute local API tests...."
          npx playwright test tests/User.Api.spec.ts --workers=1

      - name: Users Empty Array
        run: |
          echo "Running Playwright to execute local API tests..."
          npx playwright test tests/Users.EmptyArray.Api.spec.ts --workers=1
